// samples/msal-browser-samples/vue3-sample-app/src/views/Home.vue
<template>
  <div class="home">
    <span v-if="!isAuthenticated">Please sign-in to see your profile information.</span>
    <el-button v-else type="primary" v-on:click="goToProfile">Request Profile Information</el-button>
  </div>
</template>

<script setup lang="ts">
import { useRouter } from "vue-router";
import { useIsAuthenticated } from "../composition-api/useIsAuthenticated";

const isAuthenticated = useIsAuthenticated();

const router = useRouter();

function goToProfile() {
  router.push("/profile");
}
</script>

// samples/msal-react-samples/react-router-sample/src/pages/Home.jsx
import { AuthenticatedTemplate, UnauthenticatedTemplate } from "@azure/msal-react";
import Button from "@material-ui/core/Button";
import Typography from "@material-ui/core/Typography";
import { Link as RouterLink } from "react-router-dom";

export function Home() {
  return (
      <>
          <AuthenticatedTemplate>
              <Button component={RouterLink} to="/profile" variant="contained" color="primary">Request Profile Information</Button>
          </AuthenticatedTemplate>

          <UnauthenticatedTemplate>
            <Typography variant="h6">
              <center>Please sign-in to see your profile information.</center>
            </Typography>
          </UnauthenticatedTemplate>
      </>
  );
}
