// samples/msal-browser-samples/vue3-sample-app/src/components/WelcomeName.vue
<template>
    <div class="welcome-name">
        <span v-if="!!name">Welcome, {{name}}</span>
        <i class="el-icon-user"></i>
    </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useMsal } from '../composition-api/useMsal';

const { accounts } = useMsal();

const name = computed(() => {
    if (accounts.value.length > 0) {
        const name = accounts.value[0].name;
        if (name) {
            return name.split(" ")[0];
        }
    }
    return "";
});
</script>

<style>
.welcome-name {
    color: #fff;
}
</style>

// samples/msal-react-samples/b2c-sample/src/ui-components/WelcomeName.jsx
import { useEffect, useState } from "react";
import { useMsal } from "@azure/msal-react";
import Typography from "@material-ui/core/Typography";

const WelcomeName = () => {
    const { accounts } = useMsal();
    const [name, setName] = useState(null);

    useEffect(() => {
        if (accounts.length > 0) {
            setName(accounts[0].name.split(" ")[0]);
        } else {
            setName(null);
        }
    }, [accounts]);

    if (name) {
        return <Typography variant="h6">Welcome, {name}</Typography>;
    } else {
        return null;
    }
};

export default WelcomeName;
