// samples/msal-react-samples/react-router-sample/src/pages/Redirect.jsx
// This page serves the redirect bridge for MSAL authentication
// It's excluded from MsalProvider wrapper in App.js to prevent MSAL from processing the hash
import { useEffect } from "react";
import { broadcastResponseToMainFrame } from "@azure/msal-browser/redirect-bridge";

export function Redirect() {
    useEffect(() => {
        // Call broadcastResponseToMainFrame when component mounts
        broadcastResponseToMainFrame().catch((error) => {
            console.error("Error broadcasting response to main frame:", error);
        });
    }, []);

    return (
        <div>
            <p>Processing authentication...</p>
        </div>
    );
}

// samples/msal-angular-samples/angular-standalone-sample/src/app/redirect/redirect.component.ts
import { Component, OnInit } from '@angular/core';
import { broadcastResponseToMainFrame } from '@azure/msal-browser/redirect-bridge';

@Component({
  selector: 'app-redirect',
  standalone: true,
  template: '<p>Processing authentication...</p>',
})
export class RedirectComponent implements OnInit {
  ngOnInit(): void {
    // Call broadcastResponseToMainFrame when component initializes
    broadcastResponseToMainFrame().catch((error: Error) => {
      console.error('Error broadcasting response to main frame:', error);
    });
  }
}
