// samples/msal-react-samples/gatsby-sample/src/pages/profile.js
import React, { useEffect, useState } from "react";

// Msal imports
import { MsalAuthenticationTemplate, useMsal, useAccount } from "@azure/msal-react";
import { InteractionStatus, InteractionType, InteractionRequiredAuthError } from "@azure/msal-browser";
import { loginRequest } from "../authConfig";

// Sample app imports
import Layout from "../components/Layout";
import { ProfileData } from "../components/ProfileData";
import { Loading } from "../components/Loading";
import { ErrorComponent } from "../components/ErrorComponent";
import { callMsGraph } from "../utils/MsGraphApiCall";

// Material-ui imports
import Paper from "@material-ui/core/Paper";

const ProfileContent = () => {
    const { instance, accounts, inProgress } = useMsal();
    const account = useAccount(accounts[0] || {});
    const [graphData, setGraphData] = useState(null);

    useEffect(() => {
        if (account && !graphData && inProgress === InteractionStatus.None) {
            const request = {
                ...loginRequest,
                account: account
            };
            instance.acquireTokenSilent(request).then((response) => {
                callMsGraph(response.accessToken).then(response => setGraphData(response));
            }).catch((e) => {
                if (e instanceof InteractionRequiredAuthError) {
                    instance.acquireTokenRedirect(request);
                }
            });
        }
    }, [account, inProgress, instance, graphData]);
  
    return (
        <Paper>
            { graphData ? <ProfileData graphData={graphData} /> : null }
        </Paper>
    );
};

const Profile = () => {
    const authRequest = {
        ...loginRequest
    };

    return (
        <Layout>
            <MsalAuthenticationTemplate 
                interactionType={InteractionType.Redirect} 
                authenticationRequest={authRequest} 
                errorComponent={ErrorComponent} 
                loadingComponent={Loading}
            >
                <ProfileContent />
            </MsalAuthenticationTemplate>
        </Layout>
      )
};

export default Profile;

// samples/msal-browser-samples/vue3-sample-app/src/views/Profile.vue
<template>
  <div v-if="state.resolved">
	<p>Name: {{ state.data.displayName }}</p>
	<p>Title: {{ state.data.jobTitle }}</p>
	<p>Mail: {{ state.data.mail }}</p>
	<p>Phone: {{ state.data.businessPhones[0] }}</p>
	<p>Location: {{ state.data.officeLocation }}</p>
  </div>
</template>

<script setup lang="ts">
import { useMsal } from "../composition-api/useMsal";
import { InteractionRequiredAuthError, InteractionStatus } from "@azure/msal-browser";
import { reactive, onMounted, watch } from 'vue'
import { loginRequest } from "../authConfig";
import { callMsGraph } from "../utils/MsGraphApiCall";

const { instance, inProgress } = useMsal();

const state = reactive({
	resolved: false,
	data: {}
});

async function getGraphData() {
    const response = await instance.acquireTokenSilent({
        ...loginRequest
    }).catch(async (e) => {
        if (e instanceof InteractionRequiredAuthError) {
            await instance.acquireTokenRedirect(loginRequest);
        }
        throw e;
    });
	if (inProgress.value === InteractionStatus.None) {
		const graphData = await callMsGraph(response.accessToken);
		state.data = graphData;
		state.resolved = true;
		stopWatcher();
	}
}

onMounted(() => {
	getGraphData();
});

const stopWatcher = watch(inProgress, () => {
	if (!state.resolved) {
		getGraphData();
	}
});
</script>
