// samples/msal-angular-samples/angular-modules-sample/src/app/redirect/redirect.component.ts
import { Component, OnInit } from '@angular/core';
import { broadcastResponseToMainFrame } from '@azure/msal-browser/redirect-bridge';

@Component({
  selector: 'app-redirect',
  template: '<p>Processing authentication...</p>',
  standalone: false
})
export class RedirectComponent implements OnInit {
  ngOnInit(): void {
    // Call broadcastResponseToMainFrame when component initializes
    broadcastResponseToMainFrame().catch((error: Error) => {
      console.error('Error broadcasting response to main frame:', error);
    });
  }
}

// samples/msal-react-samples/nextjs-sample/pages/redirect.js
// This page serves the redirect bridge for MSAL authentication
// It's excluded from MsalProvider wrapper in _app.js to prevent MSAL from processing the hash
import { useEffect } from "react";
import { broadcastResponseToMainFrame } from "@azure/msal-browser/redirect-bridge";

export default function Redirect() {
  useEffect(() => {
    // Call broadcastResponseToMainFrame when component mounts
    broadcastResponseToMainFrame().catch((error) => {
      console.error("Error broadcasting response to main frame:", error);
    });
  }, []);

  return (
    <div>
      <p>Processing authentication...</p>
    </div>
  );
}
